### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for FurnitureLib

### ISSUE THREAD

**Issue by andris155** [Ste3et/FurnitureLib#12]
```
[18:22:35] [Netty Epoll Server IO #0/ERROR]: [FurnitureLib] Unhandled exception occured in onPacketReceiving(PacketEvent) for FurnitureLib
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_101]
    at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_101]
    at de.Ste3et_C0st.FurnitureLib.Events.FurnitureEvents$2.onPacketReceiving(FurnitureEvents.java:105) ~[FurnitureLib.jar:?]
    at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
    at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
    at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
    at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
    at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
    at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
    at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-887]
    at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched_1.10.2.jar:git-Paper-887]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.10.2.jar:git-Paper-887]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[18:22:35] [Netty Epoll Server IO #0/ERROR]: Parameters: 
  net.minecraft.server.v1_10_R1.PacketPlayInSteerVehicle@74b0fcd2[
    a=0.0
    b=0.98
    c=false
    d=false
  ]

```

**Comment by Ste3et** [comment]
How do you generate the bug i cannot reproduce this sorry

**Comment by andris155** [comment]
I don't know. Randomly error in console.

**Comment by Ste3et** [comment]
have you the newest protocllib version and the newest Spigot version ?

**Comment by andris155** [comment]
I use:
ProtocolLib 4.1.0-b325
Paper 887

**Comment by andris155** [comment]
```
[20:36:17] [Netty Epoll Server IO #2/ERROR]: [FurnitureLib] Unhandled exception occured in onPacketReceiving(PacketEvent) for FurnitureLib
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_101]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_101]
	at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.isArmorStand(FurnitureManager.java:125) ~[FurnitureLib.jar:?]
	at de.Ste3et_C0st.FurnitureLib.Events.FurnitureEvents$1.onPacketReceiving(FurnitureEvents.java:33) ~[FurnitureLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.10.2.jar:git-Paper-910]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[20:36:17] [Netty Epoll Server IO #2/ERROR]: Parameters: 
  net.minecraft.server.v1_10_R1.PacketPlayInUseEntity@6f2e3397[
    a=1480809
    action=ATTACK
    c=<null>
    d=<null>
  ]
```

**Comment by andris155** [comment]
```
[15:01:36] [Netty Epoll Server IO #2/ERROR]: [FurnitureLib] Unhandled exception occured in onPacketReceiving(PacketEvent) for FurnitureLib
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_101]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_101]
	at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.isArmorStand(FurnitureManager.java:125) ~[FurnitureLib.jar:?]
	at de.Ste3et_C0st.FurnitureLib.Events.FurnitureEvents$1.onPacketReceiving(FurnitureEvents.java:33) ~[FurnitureLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched_1.10.2.jar:git-Paper-910]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.10.2.jar:git-Paper-910]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[15:01:36] [Netty Epoll Server IO #2/ERROR]: Parameters: 
  net.minecraft.server.v1_10_R1.PacketPlayInUseEntity@3b1b4763[
    a=561891
    action=INTERACT_AT
    c=(-0.2646763026714325, 1.600000023841858, -0.05610176920890808)
    d=MAIN_HAND
  ]

```
