### ISSUE TITLE
1.14 not working

### ISSUE THREAD

**Issue by kiritodragneel** [Ste3et/FurnitureLib#49]
Hello, 
  using the most recent version 2.1.1
whenever I try to place any items I get the follow error 

`[16:15:24] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
[16:15:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651)
[16:15:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640)
[16:15:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403)
[16:15:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786)
[16:15:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.entity.fEntity.send(fEntity.java:261)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.ObjectID.lambda$updatePlayerView$0(ObjectID.java:92)
[16:15:24] [Server thread/WARN]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[16:15:24] [Server thread/WARN]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.ObjectID.updatePlayerView(ObjectID.java:92)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.ObjectID.send(ObjectID.java:204)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.ObjectID.sendAll(ObjectID.java:205)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.send(FurnitureManager.java:117)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.FurnitureHelper.send(FurnitureHelper.java:62)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.Furniture.Objects.RPG.weaponStand.spawn(weaponStand.java:263)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.Furniture.Objects.RPG.weaponStand.<init>(weaponStand.java:47)
[16:15:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:15:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:15:24] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:15:24] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.spawn(FurnitureLib.java:430)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.Events.ChunkOnLoad.spawn(ChunkOnLoad.java:197)
[16:15:24] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.Events.ChunkOnLoad$1.run(ChunkOnLoad.java:65)
[16:15:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[16:15:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[16:15:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008)
[16:15:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[16:15:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
[16:15:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
[16:15:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by Ste3et** [comment]
I think it is a ProtococolLib erro

`com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) `

**Comment by kiritodragneel** [comment]
So how would I fix?

**Comment by Ste3et** [comment]
Sorry but i can't fix this error for you. It is something missing in your runtime JavaJRE please update that and if the error appears after JavaJRE update please ask the author of ProtocolLib maybe he have another informations for you. https://github.com/dmulloy2/ProtocolLib/
