### ISSUE TITLE
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig

### ISSUE THREAD

**Issue by Dymeth** [Ste3et/FurnitureLib#54]
Error occurred while enabling FurnitureLib v2.1.8 (Is it up to date?)
```
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig
	at de.Ste3et_C0st.FurnitureLib.Database.SQLManager.initialize(SQLManager.java:37) ~[?:?]
	at de.Ste3et_C0st.FurnitureLib.Database.SQLManager.<init>(SQLManager.java:29) ~[?:?]
	at de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.onEnable(FurnitureLib.java:414) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-652]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-652]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-652]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-652]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-652]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-652]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-652]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-652]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-652]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-652]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-652]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-652]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	... 14 more
```

> about
This server is running Paper version git-Paper-655 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Previous version: git-Paper-652 (MC: 1.13.2)
Checking version, please wait...
You are running the latest version

> about FurnitureLib
FurnitureLib version 2.1.8
The FurnitureLib is an API to create packet based entity creations for Spigot based Minecraft Servers.
Website: https://dicecraft.de/furniture/
Author: Ste3et_C0st

> about ProtocolLib
ProtocolLib version 4.5.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

> about Vault
Vault version 1.7.2-b107
Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
Website: https://dev.bukkit.org/projects/vault
Authors: cereal, Sleaker and mung3r

> about LightAPI
LightAPI version 3.4.2
Bukkit Library for create invisible light source
Authors: BeYkeRYkt and Qveshn

> about ProtectionLib
ProtectionLib version 0.9.8
${project.description}
Website: ${project.url}
Author: Ste3et_C0st

**Comment by Dymeth** [comment]
Fixed in last version on SpigotMC
