### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by TwinkleToes777** [Ste3et/FurnitureLib#79]
```
[WARN]: java.lang.ClassNotFoundException: net.minecraft.world.entity.Entity
[WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.Utilitis.EntityID.<clinit>(EntityID.java:26)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.main.entity.fEntity.<init>(fEntity.java:36)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.main.entity.fArmorStand.<init>(fArmorStand.java:35)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.readEntity(FurnitureManager.java:166)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.readNBTtag(Modelschematic.java:83)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.lambda$loadEntities$1(Modelschematic.java:132)
[WARN]:        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[WARN]:        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.loadEntities(Modelschematic.java:126)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.loadEntitiesTypo(Modelschematic.java:115)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.<init>(Modelschematic.java:53)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelHandler.<init>(ModelHandler.java:39)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.Crafting.Project.<init>(Project.java:90)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelFileLoader.loadModelFile(ModelFileLoader.java:29)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelFileLoader.lambda$loadModelFiles$0(ModelFileLoader.java:21)
[WARN]:        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelFileLoader.loadModelFiles(ModelFileLoader.java:21)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.SchematicLoader.ProjectManager.loadProjectFiles(ProjectManager.java:14)
[WARN]:        at de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.onEnable(FurnitureLib.java:410)
[WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596)
[WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309)
[WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
```
I am using 1.16.5 and FurnitureLib 2.7.1

**Comment by Ste3et** [comment]
Please try these devbuild and give feedback about it https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.18.x&buildNummer=495863579
