### ISSUE TITLE
Does not work on 1.20.2 PaperMC

### ISSUE THREAD

**Issue by lockieluke** [Ste3et/FurnitureLib#95]
<img width="838" alt="image" src="https://github.com/Ste3et/FurnitureLib/assets/25424409/6eb2afca-4826-4406-9609-c760dd817dc4">

**Comment by lockieluke** [comment]
none of my furnitures display correctly, when you break it the base block of the furniture drops

**Comment by Ste3et** [comment]
Please Take a Look in upcomming paper Versions, These isn't a furniturelib related issue

**Comment by lockieluke** [comment]
so how should I approach this issue

**Comment by Ste3et** [comment]
Downgrade your paper to a stable build

**Comment by Ste3et** [comment]
I have take a look into it and it looks like an ProtocolLib issue.

```
[17:40:25 WARN]: java.lang.RuntimeException: Failed to make NMS copy of ItemStack{PLAYER_HEAD x 1, SKULL_META:{meta-type=SKULL, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Deepslate Multi Ore"}],"text":""}, skull-owner=CraftPlayerProfile [uniqueId=04049c90-d3e9-4621-9caf-0000aaa52663, name=, properties={textures=[{name=textures, value=eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmMyMTc5OWZkYjIzZWE0NDQzMmQ2YTQ0OWM3NDdkM2JiZDU2NmNjMjkzOTJjMGZlMzE1M2E5ZGRjYTVlNWQ1In19fQ==, signature=null}]}]}}
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getMinecraftItemStack(MinecraftReflection.java:1338)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$15.getGeneric(BukkitConverters.java:911)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$15.getGeneric(BukkitConverters.java:903)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.WrappedWatchableObject.getUnwrapped(WrappedWatchableObject.java:153)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:497)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:515)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.main.entity.fItem_display.setItemStack(fItem_display.java:72)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.main.entity.fItem_display.loadMetadata(fItem_display.java:100)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.readNBTtag(Modelschematic.java:85)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.lambda$loadEntities$1(Modelschematic.java:138)
[17:40:25 WARN]:        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[17:40:25 WARN]:        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)[17:40:25 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.loadEntities(Modelschematic.java:132)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.loadEntitiesTypo(Modelschematic.java:121)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.Modelschematic.<init>(Modelschematic.java:52)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelHandler.<init>(ModelHandler.java:45)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.Crafting.Project.<init>(Project.java:87)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelFileLoader.loadModelFile(ModelFileLoader.java:29)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelFileLoader.lambda$loadModelFiles$0(ModelFileLoader.java:21)
[17:40:25 WARN]:        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.ModelLoader.ModelFileLoader.loadModelFiles(ModelFileLoader.java:21)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.SchematicLoader.ProjectManager.loadProjectFiles(ProjectManager.java:14)
[17:40:25 WARN]:        at FurnitureLib-3.1.2.jar//de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.onEnable(FurnitureLib.java:353)
[17:40:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[17:40:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[17:40:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[17:40:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[17:40:25 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644)
[17:40:25 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555)
[17:40:25 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
[17:40:25 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[17:40:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[17:40:25 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
[17:40:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[17:40:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:40:25 WARN]: Caused by: java.lang.IllegalStateException: Unable to invoke method public static net.minecraft.world.item.ItemStack org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(org.bukkit.inventory.ItemStack)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getMinecraftItemStack(MinecraftReflection.java:1336)
[17:40:25 WARN]:        ... 35 more
[17:40:25 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
[17:40:25 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148)[17:40:25 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659)[17:40:25 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:60)
[17:40:25 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23)
[17:40:25 WARN]:        ... 36 more
```

stay tuned i try to work araound but i cannot say something about how long it takes, Paper 1.20.2 241 works fine for me
